package com.jordansilva.foursquarenearby.infrastructure.util

class Constants {
    object API {
        val FOURSQUARE = "https://api.foursquare.com/v2/"
        val FOURSQUARE_VERSION = "20180323"
        val FOURSQUARE_CLIENT_ID = "XXN5Y3XO4I3AFFNHHP51JHWFOEVAPZOQ0X1HFWPXNHT02OXR"
        val FOURSQUARE_CLIENT_SECRET = "GPALFTYITTPBSB5VM1QA101PDBU3F2P530BNQLBDL5EG5UMR"
//        val FOURSQUARE_CLIENT_ID = "BXRUJ2F5NHKRUOKG4KZFVOT2VLAJ2GLDVG3SP50DQQFC2C32"
//        val FOURSQUARE_CLIENT_SECRET = "H0AAVX1J4ENUVK3H5HDAFC4AGUP1AF30LKHXQWN4GS5E2EOD"
    }
}